---
- name: Install snap
  become: true
  ansible.builtin.package:
    name: snapd
    state: present

- name: Install VSCode
  become: true
  community.general.snap:
    name: code
    state: present
    classic: true