---
- name: Create folder strucutre
  hosts: localhost
  tasks:
  - name: Check if folder exists
    ansible.builtin.stat:
      path: "~/projects"
    register: project_folder

  - name: Create projects folder
    ansible.builtin.file:
      path: "~/projects"
      state: directory
      mode: 0644
    when: not project_folder.stat.exists 


- name: Create ssh keys
  hosts: localhost
  tasks:
  - name: Create ssh keys
    community.crypto.openssh_keypair:
      path: "~/.ssh/id_{{ item }}"
      type: rsa
      size: 4096
      state: present
      force: no
    with_items:
    - github
    - gitlab
    - zinsoldat

- name: Install development tools
  hosts: localhost
  roles:
  - role: tools/git
    tags: git   
  - role: tools/zsh
    tags: zsh
  - role: tools/docker
    tags: container/docker
  - role: tools/podman
    tags: container/podman

- name: Install development Languages
  hosts: localhost
  roles:
  - role: languages/go
    tags: go