---
- name: Install packages
  become: yes
  ansible.builtin.apt:
    name: "{{ required_packages }}"
    state: present
    update_cache: yes
    force_apt_get: yes

- name: Add docker GPG key
  become: yes
  ansible.builtin.apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Save the current Ubuntu release version into a variable
  ansible.builtin.command: lsb_release -cs
  register: ubuntu_version
  changed_when: ubuntu_version.rc != 0
  
- name: Add Docker Repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
    state: present

- name: Update apt packages
  become: true
  apt:
    update_cache: yes
    force_apt_get: yes
    
- name: Install Docker
  become: true
  ansible.builtin.apt:
    name: docker-ce
    state: present
    force_apt_get: yes

- name: Create docker group
  become: true
  ansible.builtin.group:
    name: "{{ group }}"
    state: present

- name: Adding user {{ username }} to docker group
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    groups: "{{ group }}"
    append: yes

- name: Get latest docker-compose release tag
  ansible.builtin.uri:
    url: https://api.github.com/repos/docker/compose/releases/latest
    return_content: true
  register: latest_release_json

- name: Install Docker Compose
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/{{ latest_release_json.json.name }}/docker-compose-linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    mode: 0755