---
- name: Install git
  ansible.builtin.apt:
    name: git
    state: present

- name: Set default branch git
  community.general.git_config:
    scope: global
    name: init.defaultBranch
    value: main

- name: Set username
  community.general.git_config:
    scope: global
    name: user.name
    value: "{{ username }}"

- name: Set email
  community.general.git_config:
    scope: global
    name: user.email
    value: "{{ email }}"