---
- name: Install packages (debian)
  ansible.builtin.import_tasks: debian.yml
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Install packages  (arch)
  ansible.builtin.import_tasks: arch.yml
  when: ansible_distribution == 'Archlinux'

- name: Set default branch git
  community.general.git_config:
    scope: global
    name: init.defaultBranch
    value: main

- name: Set username
  community.general.git_config:
    scope: global
    name: user.name
    value: "{{ username }}"

- name: Set email
  community.general.git_config:
    scope: global
    name: user.email
    value: "{{ email }}"