---
- name: Cretae folder
  ansible.builtin.file:
    path: "{{ go_path }}"
    state: directory
    mode: 0644

- name: Download go archive
  ansible.builtin.get_url:
    url: "https://go.dev/dl/go{{ version }}.linux-amd64.tar.gz"
    dest: /tmp/go.tar.gz

- name: Delete old installation
  become: yes
  ansible.builtin.file:
    path: "{{ installation_dest }}/go"
    state: absent

- name: Extract go archive
  become: yes
  ansible.builtin.unarchive:
    src: /tmp/go.tar.gz
    dest: "{{ installation_dest }}"

- name: Get user
  ansible.builtin.user:
    name: "{{ username }}"
  register: user_to_setup

- name: Add to path for bash
  become: yes
  ansible.builtin.template:
    src: env.sh.j2
    dest: /etc/profile.d/go.sh
    mode: 0644
  when: "'bash' in user_to_setup.shell"

- name: Check if env is already set
  ansible.builtin.shell:
    cmd: "cat /home/{{ username }}/.zprofile | grep GOROOT | wc -l"
  register: goroot_set
  when: "'zsh' in user_to_setup.shell"

- name: Add to path for zsh
  ansible.builtin.lineinfile:
    dest: "/home/{{ username }}/.zprofile"
    line: |
      GOROOT={{ installation_dest }}/go
      GOPATH=/home/{{ username }}/go
      PATH=$PATH:$GOROOT/bin:$GOPATH/bin
    state: present
    create: yes
    mode: 0644
  when: "'zsh' in user_to_setup.shell and goroot_set.stdout == '0'" 