---
- name: Check if go is installed
  ansible.builtin.import_tasks: check_installed.yml

- name: install go
  ansible.builtin.import_tasks: install.yml
  when: not go_installed or go_version_installed != version