---
- name: Install packages (debian)
  ansible.builtin.import_tasks: debian.yml
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Install packages  (arch)
  ansible.builtin.import_tasks: arch.yml
  when: ansible_distribution == 'Archlinux'

- name: Set zsh as default shell
  become: true
  ansible.builtin.command:
    cmd: "chsh -s /usr/bin/zsh"
  register: zsh_default_shell
  changed_when: zsh_default_shell.rc != 0

- name: Check if oh-my-zsh is installed
  ansible.builtin.stat:
    path: "/home/{{ username }}/.oh-my-zsh"
  register: zsh_folder

- name: Download setup script
  ansible.builtin.get_url:
    url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/zsh_install.sh
  when: not zsh_folder.stat.exists

- name: Set as default shell
  ansible.builtin.script:
    cmd: /tmp/zsh_install.sh --unattended
  when: not zsh_folder.stat.exists

