---
- name: Install packages
  become: yes
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
  - fonts-powerline
  - curl

- name: Install zsh
  become: yes
  ansible.builtin.apt:
    name: zsh
    state: present
  register: zsh_install

- name: Set zsh as default shell
  become: true
  ansible.builtin.command:
    cmd: "chsh -s /usr/bin/zsh"
  register: zsh_default_shell
  changed_when: zsh_default_shell.rc != 0

- name: Check if oh-my-zsh is installed
  ansible.builtin.stat:
    path: "/home/{{ username }}/.oh-my-zsh"
  register: zsh_folder

- name: Download setup script
  ansible.builtin.get_url:
    url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/zsh_install.sh
  when: not zsh_folder.stat.exists

- name: Set as default shell
  ansible.builtin.script:
    cmd: /tmp/zsh_install.sh --unattended
  when: not zsh_folder.stat.exists

